### ISSUE TITLE
Bootstrap VS Foundation VS Materialize

### ISSUE THREAD

**Issue by mdantonio** [pdonorio/angulask#14]
just a reminder for now, no resources added to this card.

**Comment by pdonorio** [comment]
I am trying to create a better extensibility for these three frameworks.

**Comment by pdonorio** [comment]
Here is the new branch with the frameworks folder:

https://github.com/pdonorio/angulask/tree/frameworks/angulask/templates/frameworks

Also found a solution about whitespaces in jinja2 templates here: http://jinja.pocoo.org/docs/dev/templates/#whitespace-control

**Comment by pdonorio** [comment]
So to recap:
- bootstrap (3.3.6) needs angular-strap
- materialize (almost v1.0) needs angular-materialize (installed both with bower)
- foundation seems to integrate angular modules natively: http://foundation.zurb.com/apps/docs/#!/angular-modules

**Comment by mdantonio** [comment]
At the moment Bootstrap won ... but who knows what the future holds
