### ISSUE TITLE
How to share the token between Flask and AngularJS

### ISSUE THREAD

**Issue by mdantonio** [pdonorio/angulask#15]

**Comment by pdonorio** [comment]
Waiting for pdonorio/rest-mock#3

**Comment by pdonorio** [comment]
Angular could call domain/getlogin which is an endpoint implemented in flask frontend.

This endpoint should sniff the token via server and reroute it to angular.

So the new schema would be:

USER(credentials) -> angular(satellizer?) -> flask(getlogin_frontend) -> flask(security_login)

**Comment by pdonorio** [comment]
@mdantonio can study on angular https://satellizer.herokuapp.com/#/

**Comment by pdonorio** [comment]
Ok, this has been done a long time ago XD
