### ISSUE TITLE
Unable to call API from Flask

### ISSUE THREAD

**Issue by mdantonio** [pdonorio/angulask#18]
I'm trying to perform an API call from Flask via Request library to implement the three-way login schema as discussed (angularjs -> flask_frontend -> flask_api)

I'm able to perform request get/post calls to any external resource (google, github, etc) but i'm not able to call API:

This request remains stuck just until a timeout
request.get('http://130.186.13.86:8081/login') 

requests.exceptions.Timeout: HTTPConnectionPool(host='130.186.13.86', port=8081): Read timed out. (read timeout=5)

from inside the flask docker machine the call works with no problem via curl

curl -X GET http://130.186.13.86:8081/login

**Comment by pdonorio** [comment]
I will test the problem on docker from a container to another.
The first container will be running the API and the second via link will launch a Python request to those API login endpoint

**Comment by pdonorio** [comment]
(next time copy/paste the snippet of request :P)

**Comment by pdonorio** [comment]
This works for me:

``` python
import requests
import simplejson as json

URL = 'http://%s:%s' % (NODE, PORT)
LOGIN_URL = URL + '/login'
HEADERS = {'content-type': 'application/json'}
payload = {'email': USER, 'password': PW}
r = requests.post(LOGIN_URL, data=json.dumps(payload), headers=HEADERS)

print(r, r.url)
print("RESPONSE:")
try:
    print(r.json())
except:
    print(r.text)
```

Check if it works for you too and we can close the issue.

**Comment by mdantonio** [comment]
I modified the API call implementation to reflect your own version... but i get the same "read timed out" exception... maybe some difference that i'm not able to see...

**Comment by pdonorio** [comment]
The problem was related to who you are calling.

You have to set your /mylogin endpoint inside Flask Frontend, not Flask API.

**Comment by pdonorio** [comment]
Not the real workflow

**Comment by pdonorio** [comment]
Not the real workflow
