### ISSUE TITLE
Problems bower container

### ISSUE THREAD

**Issue by mdantonio** [pdonorio/angulask#4]

**Comment by mdantonio** [comment]
From the angulask docker-compose.yml  I start the bower container, then I log in the container via docker exec

Once in the container i'm logged with develop account (instead of root) and i experience permission denied errors on some folders... what i'm missing?

**Comment by pdonorio** [comment]
Which folders?

We should probably share a screen / tmux /tmate

**Comment by mdantonio** [comment]
> Which folders?

Ehm... all of them... all files and folders belongs to root:root but i'm _developer_

```
developer@725f2578f67f:/web$ whoami
developer
developer@725f2578f67f:/web$ ls -l
total 20
-rw-r--r-- 1 root root  926 Nov  9 06:58 bower.json
drwxr-xr-x 2 root root 4096 Nov  9 07:34 bower_components
-rw-r--r-- 1 root root  681 Nov  9 06:58 gulpfile.js
-rw-r--r-- 1 root root 1475 Nov  9 06:58 package.json
drwxr-xr-x 3 root root 4096 Nov  9 06:58 src

```

**Comment by mdantonio** [comment]
The problem explained:

the bower container runs as developer (this is required by... something very smart, but i don't remember what, nevermind) but the source directory (monted as volume in the container) belongs to root... 

Solution: change owner to the source directory from _root_ to _ubuntu_

Then, to use the bower container

```
cd angulask/containers
docker-compose up -d bower
docker-compose run bower "npm install && bower install"
docker-compose stop
```

**Comment by pdonorio** [comment]
Never work with root user :plus1: 

A gentle reminder for me: check in the future how to map a user on every docker image
